### ISSUE TITLE
method to validate single field

### ISSUE THREAD

**Issue by robhicks** [posabsolute/jQuery-Validation-Engine#393]
Is there a method to validate a single field? 

Here's a real world scenario. A user profie editor. The user can add as many email address as the user wants. One of them needs to be the default email address for the user. The user is presented with a link to make an email address the default email address. When the link is clicked, the email address field needs to be validated. It is not important to validate the rest of the form.  In fact, it clutters up the screen.

**Comment by omairrazam** [comment]
this post is old but i can see that answer to Robhicks issue has not been given. i had faced the same issue and had spent alot of time finding its solution. 
issue : callback is not firing
there is a path where form submits( i.e form Post field), may be php file or in codeigniter a function, that function must return an array of data, that data is the posted that of the form, we need to make an array of this data and then return it... this data is then passed to callback function and in your case form is the parameter that contains this data.... here is my that post function which i wrote as per my requirement this is codeigniter function
public function ajax_valid_main() {
		
		/**
		 * *********************************
		 * this function is used for server side validation
		 * this is required by Validation Engine
		 * Validation Engine code is post method...
		 * so this function is used to return something
		 * for validation engine to work
		 * *********************************
		 */
		$from = "";
		$to = "";
		
		if (isset ( $_POST ['search_by'] )) {
			$search_by = $_POST ['search_by'];
		}
		
		if ($search_by == "" && ! isset ( $search_by )) {
			$result = array ('status' => 0 );
			echo json_encode ( $result );
			return;
		}
		
		$result = array ('search_by' => $search_by );
		
		if (isset ( $_POST ['s_uname'] )) {
			$name = $_POST ['s_uname'];
			$name = escape_quotes ( $name );
			$result = array_merge ( $result, array ('s_uname' => $name ) );
			$result = array_merge ( $result, array ('key' => $name ) );
		}
		if (isset ( $_POST ['s_uid'] )) {
			
			$uid = $_POST ['s_uid'];
			$uid = escape_quotes ( $uid );
			$result = array_merge ( $result, array ('s_uid' => $uid ) );
			$result = array_merge ( $result, array ('key' => $uid ) );
		}
		if (isset ( $_POST ['s_email'] )) {
			$email = $_POST ['s_email'];
			$email = escape_quotes ( $email );
			$result = array_merge ( $result, array ('s_email' => $email ) );
			$result = array_merge ( $result, array ('key' => $email ) );
		}
		
		echo json_encode ( $result );
	}


i guess if we just return an empty json array it will still work.... this is subject to hit and trial.
i hope this will help :)

**Comment by lubnashaikh** [comment]
why u send it 2 me???

**Comment by omairrazam** [comment]
lols… i just replied on a forum … There was an issue discussed a few years back but no one replied the correct solution. so thought although post is too old but may be in future my answer might help someone.

**Comment by lubnashaikh** [comment]
heheheh ok

**Comment by omairrazam** [comment]
hehehhee

**Comment by lubnashaikh** [comment]
are u facing problm in validation of single field?

**Comment by omairrazam** [comment]
yes

**Comment by lubnashaikh** [comment]
i also had same problm.tdz y post solution.didn't it help u?

**Comment by omairrazam** [comment]
actually my issue was little different…. i understand validation engine a lot well now but i was using it with jtable and was having issues while using asynchronous ajax calls.
you can help me only if you have some experience with jtable.  issue is:
in normal case for asynchronous ajax calls all data is returned to our callback function where we then submit the form but in jtable it has its own event handler like for for submission and i was trying to apply asynchronous ajax field
validation on its form at client side but when i wrote the syntax of asynchronous call in jtable form submitting handler, there was some map-functioning..

when i was brought to your form, my issue was not stated there but there was a person's issue that was not answered and i knew the solution, so i posted my solution there.
