### ISSUE TITLE
Doesn't validate some fields that are "hidden" but visible

### ISSUE THREAD

**Issue by mperham** [posabsolute/jQuery-Validation-Engine#404]
I have a form which has size 0x0 (due to accidentally being styled as "display:inline") but has content which is clearly visible on the screen.  JQV fails to validate fields because the parent form is considered :hidden by jquery even though the content is visible and editable.

What's the right thing to do here?  Maybe a note in the documentation about validation being contingent on parent visibility?

**Comment by Nymos** [comment]
There is no workaround to fix this?
