### ISSUE TITLE
Ajax Field/Form Validation

### ISSUE THREAD

**Issue by rjhilgefort** [posabsolute/jQuery-Validation-Engine#502]
I am attempting to implement an ajax validation on a particular field in a form.

I seem to have gotten it working for the most part, ie- I am seeing the validator return "OK" when expected, and throw an error when expected. However, I am unable to successfully submit the form... in all cases. Even when the value has been validated successfully, the form submission will continue to say that the ajax validated field is invalid.

My implementation is quite cumbersome to recreate (in a working way), but I would be happy to try and post all relevant code. I just thought I would describe the issue first to see if there was something obvious I might be missing. Thank you in advance for your reply.

**Comment by bartclaeys** [comment]
Seems like this problem hasn't been fixed yet, even not in version 2.6.5, see:

https://github.com/posabsolute/jQuery-Validation-Engine/issues/954
