### ISSUE TITLE
Select Boxes do not validate with 0 values, hidden values are omitted as well.

### ISSUE THREAD

**Issue by sunalive** [posabsolute/jQuery-Validation-Engine#546]
I have select combo drop downs with the first value as 0 (in order to capture the submit for non-selected select boxes).  It works with version 1.8 with a small variation in code < || field.val() == '0'> at line 650 (edit provided by paul).  However, this case does not work in the new 2.6 version.  A note about my markup here.  I do not use IDs (as the code is auto generated).  I use the PHP array notation <element[name][]> for the element name.  I do not use the conditions in classes but in the data-validation-engine attribute (since it suits my application architecture and also keeps my code tidy and separated). I do not use a placeholder attribute either.

Another issue I have is that I use JQuery tabs which hide the < div >s for inactive tabs. This library omits the hidden fields for validation.  Is there any config available so that I can validate the hidden fields as well?

I preferred your library to JQuery validations because this looks slick (inline markup) and suits my architecture (validation conditions generate along with the corresponding fields rather than defined separately).    I really appreciate your effort and kindness to give the code for free.

**Comment by verybigelephants** [comment]
yeah, validation engine doesn't validate 0 :( i haven't found any workaround
