### ISSUE TITLE
onValidationComplete not firing

### ISSUE THREAD

**Issue by StevenLangbroek** [posabsolute/jQuery-Validation-Engine#642]
Hey guys,

I've used validationEngine for quite some time now, but I'm running into an issue with a more complex form. I've built a multi-step form using javascript, and want to use validationEngine to validate the fields on the currently active fieldset. Since I don't want the form to actually submit in the first couple of fieldsets but show the next fieldset, I thought I'd loop through the inputs in the active fieldset, 'attach' validationEngine, and then on click run 'validate' with a configuration-object. My code looks like this mostly:

```
e.preventDefault();

var fields = $('fieldset').eq(0).find('input');

fields.each(function(){
    $(this).validationEngine('attach');
});

$(fields).validationEngine('validate', {
    onValidationComplete: function(f, s){
        console.log(f);
    }
});
```

I've tried onValidationComplete, onSuccess and onFailure but none of these events fire in my case... I highly doubt this is desired behaviour, as the validation is running (If I leave a field empty it shows it's validation-prompt as expected) but the events never trigger...

**Comment by M3lkior** [comment]
onValidationComplete callback must be used in the "attach" phase like this : 

<pre>
newForms.validationEngine('attach', {
							promptPosition : "inline",
							binded : false,
							validateNonVisibleFields: true,//use to display select2 errors' messages
							onValidationComplete: function(f, s){
        console.log(f);
    }

						});
</pre>
