### ISSUE TITLE
Make the validation engine compatible with UI datepicker

### ISSUE THREAD

**Issue by posabsolute** [posabsolute/jQuery-Validation-Engine#70]
Currently the blur event get in conflict with the jquery UI action making the validation of date pretty weird

**Comment by manoj10029** [comment]
datepicker.daterangepicker({
                    singleDatePicker: true,
                    startDate: (datepicker.val() ? datepicker.val() : new Date()),
                    format: 'MM/DD/YYYY',
                });

                $('#dueDate').on('hide.daterangepicker', function(ev, picker) {
                     $(".formErrorArrow").hide(),
                     $(".formErrorContent").hide()
                });
 $('.btn-save', orderForm).on('click', function (e) {
                    orderForm.validationEngine({'scroll': false ,'autoHidePrompt':true});
                    $(".formErrorArrow").show();
                    $(".formErrorContent").show();
});

**Comment by mandrivnyk** [comment]
My solution that helped me: 
in template input element in form: 
<input type="text"  name="date" id="date" data-validation-engine="validate[required]">

in js file:

$("#date").datepicker(
        {
            beforeShow:  function ()
        {
            $("#date").removeAttr("data-validation-engine");
        }
    });
