### ISSUE TITLE
Can the showOneMessage option be for a single field?

### ISSUE THREAD

**Issue by lnong** [posabsolute/jQuery-Validation-Engine#703]
I know how to get it to work when setting this option for the whole form.  But say I have one field with 2 rules (required, and a custom one).  Currently, both error messages will show up in one prompt for this field  How can I get it to only show one message?

Can the showOneMessage option be applied to a single field, something like this:

$("#MyField").validationEngine({ showOneMessage: true });

That didnt work, but im not sure if Im using it correctly..

**Comment by mithilesh-kiprosh** [comment]
You can directly write use maxErrorsPerField in your js file. As,
$("#form").validationEngine('attach', {
      maxErrorsPerField: 1
});
