### ISSUE TITLE
required + placeholder behaviour not consistent with HTML 5 placeholder definition

### ISSUE THREAD

**Issue by plequang** [posabsolute/jQuery-Validation-Engine#729]
Hi,

Currently, the required validator does not accept a field whose value is the same as the value of the new HTML5 "placeholder" attribute.

For example, consider the placeholder code example from the HTML 5 draft 
(http://www.w3.org/TR/2013/CR-html5-20130806/forms.html#the-placeholder-attribute)

``` html
<label>Name: 
<input type="text" name="fullname" placeholder="John Ratzenberger" 
          class="validate[required]">
</label>
```

If your name is really "John Ratzenberger", then the plugin will consider you have not filled in the form.

HTML 5 states that :

> The placeholder attribute represents a short hint [...]. A hint could be a sample value "

What if the sample value is a possible value ?

I've created a small jsfiddle to demonstrate this
http://jsfiddle.net/VBeQ4/1/

**Comment by trappist** [comment]
I'm currently experiencing this 2 year old issue. +1?

**Comment by trappist** [comment]
Actually... not a bug. 8c690f39fdc6cde2a30abe4a509

This is awful though.

**Comment by ATouhou** [comment]
lol.. A client just reported this "bug" to me :P Guess the best fix for now is to something to the placeholder html so that it does not match 1:1

**Comment by poradz** [comment]
Hi, I recommend to use this fork:

https://github.com/YetiForceCompany/jQuery-Validation-Engine

We have already fixed a lot of bugs including this one.
