### ISSUE TITLE
Validation on jtable

### ISSUE THREAD

**Issue by NaniA** [posabsolute/jQuery-Validation-Engine#809]
have a Jtable in asp.ent application and it is working fine, now I wanted to add a validation logic in the same Jtable, but I am not getting the desired result, inspite of copying the same to same code from Jtable.org demo site.

Is there something else I need to do?

$('#StudentTableContainer').jtable({
        title: 'Student List',
        paging: true, //Enable paging
        sorting: true, //Enable sorting
        defaultSorting: 'Name ASC',
        actions: {
            listAction: '../User/class.aspx/GetAppPhones',
                createAction: '../User/class.aspx/AddAppPhones',
                updateAction: '../User/class.aspx/UpdateAppPhones',
                deleteAction: '../User/class.aspx/DeleteAppPhones'
        },
        fields: {
            StudentId: {
                key: true,
                create: false,
                edit: false,
                list: false
            },
            Name: {
                title: 'Name',
                width: '15%'
            },
            EmailAddress: {
                title: 'Email address',
                list: false
            },
            Password: {
                title: 'User Password',
                type: 'password',
                list: false
            },
            Gender: {
                title: 'Gender',
                width: '12%',
                options: { 'M': 'Male', 'F': 'Female' }
            },
            CityId: {
                title: 'Living city',
                width: '15%'
            },
            BirthDate: {
                title: 'Birth date',
                width: '18%',
                type: 'date',
                displayFormat: 'yy-mm-dd'
            },
            Education: {
                title: 'Education',
                list: false,
                type: 'radiobutton',
                options: { '1': 'Primary school', '2': 'High school', '3': 'University' }
            },
            About: {
                title: 'About this person',
                type: 'textarea',
                list: false
            },
            IsActive: {
                title: 'Status',
                width: '10%',
                type: 'checkbox',
                values: { 'false': 'Passive', 'true': 'Active' },
                defaultValue: 'true'
            },
            RecordDate: {
                title: 'Record date',
                width: '18%',
                type: 'date',
                displayFormat: 'yy-mm-dd',
                create: false,
                edit: false
            }
        },
        //Initialize validation logic when a form is created
        formCreated: function (event, data) {
            data.form.find('input[name="Name"]').addClass('validate[required]');
            data.form.find('input[name="EmailAddress"]').addClass('validate[required,custom[email]]');
            data.form.find('input[name="Password"]').addClass('validate[required]');
            data.form.find('input[name="BirthDate"]').addClass('validate[required,custom[date]]');
            data.form.find('input[name="Education"]').addClass('validate[required]');
            data.form.validationEngine();
        },
        //Validate form when it is being submitted
        formSubmitting: function (event, data) {
            return data.form.validationEngine('validate');
        },
        //Dispose validation logic when form is closed
        formClosed: function (event, data) {
            data.form.validationEngine('hide');
            data.form.validationEngine('detach');
        }
    });

```
//Load student list from server
$('#StudentTableContainer').jtable('load');
 });
```

I am also using the required js files:

<script src="../JScript/jquery.validationEngine-en.js" type="text/javascript"></script>

<script src="../JScript/jquery.validationEngine.js" type="text/javascript"></script>

 <link href="../CSS/validationEngine.jquery.css" rel="stylesheet" type="text/css" 

please help me anyone thanks in advance...

**Comment by laptevn** [comment]
Why do you think that you're using required js file?
You set validation logic for your table, you included CSS but you didn't included ValidationEngine script.
JTable site has a proper example.

The issue can be closed.
