### ISSUE TITLE
Adding a Custom Validation Method

### ISSUE THREAD

**Issue by davefuse** [posabsolute/jQuery-Validation-Engine#838]
Hi

I don't think that this is an issue with the plugin but i really need some assistance with it as my javascript skills are less than basic, I would like to add in a custom validation that validates whether or not your ID number is valid

The code that i am currently using to validate the ID number looks like this:

function val_sa_id(a)
{
    var b = "- South African ID is valid\n";
    var c = 0;
    var d = 0;
    var e = 0;
    var f = 0;
    if (a.length != 13)
    {
        b = "- South African ID numbers are 13 characters long\n"
    }
    else
    {
        if (parseInt(a, 10) == a)
        {
            c = parseInt(a.slice(0, 1), 10) + parseInt(a.slice(2, 3), 10) +
                parseInt(a.slice(4, 5), 10) + parseInt(a.slice(6, 7), 10) +
                parseInt(a.slice(8, 9), 10) + parseInt(a.slice(10, 11), 10);
            d = parseInt(a.slice(1, 2) + a.slice(3, 4) + a.slice(5, 6) + a.slice(
                7, 8) + a.slice(9, 10) + a.slice(11, 12), 10) \* 2;
            for (i = 0; i < parseInt(String(d)
                .length, 10); i++)
            {
                e = e + parseInt(d.toString()
                    .slice(i, i + 1), 10)
            }
            f = Right(String(10 - parseInt(Right(String(e + c), 1), 10)), 1);
            if (f != Right(String(a), 1))
            {
                b =
                    "- The ID number entered is not a valid South African ID number\n"
            }
        }
        else
        {
            b = "- South African ID numbers are made up of numbers only\n"
        }
    }
    return b
}

function Right(a, b)
{
    if (b <= 0) return "";
    else if (b > String(a)
        .length) return a;
    else
    {
        var c = String(a)
            .length;
        return String(a)
            .substring(c, c - b)
    }
}

function Left(a, b)
{
    if (b <= 0) return "";
    else if (b > String(a)
        .length) return a;
    else return String(a)
        .substring(0, b)
}

It is just getting the value from a text input and the page script looks like this:

$(document).ready(function(e) {
    $('#btnCheck').click(function(e) {
        alert(val_sa_id($('#idnr').val()));
    });
});

How would i validate the number using my method but with the jQuery-Validation-Engine script?

I would appriciate any feedback or input on this and thank you in advance!

**Comment by MB34** [comment]
Look at the funcCall section in the docs. That is how you do it, your idnr input field would look like this:
<input id="idnr" class="validate[funcCall[val_sa_id]]" value="" />
You would return b in your function just as you are. That would be the error message shown in the ValidationEngine prompt. You can test it out on jsFiddle beforehand if you'd like: https://jsfiddle.net/70c6u2u1/23/
