### ISSUE TITLE
Required prompt on file type input

### ISSUE THREAD

**Issue by MB34** [posabsolute/jQuery-Validation-Engine#842]
I don't think the required prompt should show unless there is no file selected when the form is either submitted or the validate function is called.

It currently shows immediately when you click the Choose File button, see your demo, it does it too.
http://www.position-relative.net/creation/formValidator/demos/demoFieldTypes.html

<input class="validate[required] text-input" type="file" name="file" id="file">

**Comment by MB34** [comment]
Why has no one commented on this? I believe it to be a horrible bug in this plugin.

**Comment by MB34** [comment]
Wow, almost 2 YRS ago and still no one even comments on this???

**Comment by iStefo** [comment]
I find it quite interesting that, even though you are the one experiencing this problem, expect other people to take care of it. As you are probably aware, this project is open source and encourages everyone to participate.
So I came to ask myself: If this bug has troubled you for two whole years, why haven't you taken a look at the source code and spent a few minutes or hours trying to figure out a solution?
