### ISSUE TITLE
How to apply jquery validation on 'chosen' using jQuery jtable?

### ISSUE THREAD

**Issue by ghost** [posabsolute/jQuery-Validation-Engine#850]
I have a 'select' element sponsored by chosen.js within a jQuery jtable form and I want to apply validation on it, I tried using the following code but unsuccessful!

 //Validate form when it is being submitted
 formSubmitting: function (event, data) {
 data.form.validationEngine('validate', { ingore: ':hidden:not(select)' });
 return data.form.validationEngine('validate');
 },

**Comment by AlbertAlpha** [comment]
I have the same problem with [chosen](http://harvesthq.github.io/chosen) plug-in and haven't found any elegant way to make it work without editing the plug-in core.

As chosen plug-in hides the original select element, you need to enable the validation on hidden fields in the `options`:

	validateNonVisibleFields: true

This works and validates the chosen enabled select elements, but the prompt message (at least in my case) does not appear in the correct position, so I have added those lines on `_calculatePosition` function:

	_calculatePosition: function (field, promptElmt, options) {
		...
		//Compatibility with chosen library
		if (field.hasClass("chosen-select")) {
			var chosenDiv = field.siblings('#'+field.attr('id')+'_chosen');
			fieldWidth 	= chosenDiv.width();
			fieldLeft 	= chosenDiv.position().left;
			fieldTop 	=  chosenDiv.position().top;
			fieldHeight 	=  chosenDiv.height();
		}
		...
	}

This places the prompt message in the div generated by chosen plug-in.

**Comment by AlbertAlpha** [comment]
Looking at the code it's seems to be an undocumented property you can use to achieve compatibility with chosen without modify validationEngine.js code.

Set `validateNonVisibleFields: true` as mentioned in the previous post, then add the following atributes to the `<select>`:

    <select id="idElem" class="chosen-select validate[required]" data-prompt-position="inline" data-prompt-target="idElem_chosen">
    
Error messages will appear inline below the chosen component.
