### ISSUE TITLE
Spanish dates don't work with future and past validation

### ISSUE THREAD

**Issue by EduardoUcha** [posabsolute/jQuery-Validation-Engine#851]
The format DD/MM/YYYY and DD-MM-YYYY don't work with the future(field1) and past(field2) validators.  The date format change in the message to YYYY-MM-DD and the date is not correct

![enginevalidator](https://cloud.githubusercontent.com/assets/7735554/5142681/2f86d2f8-7186-11e4-8bde-b7d8fdb82f75.PNG)

**Comment by MB34** [comment]
Modify the _parseDate method to properly format the dates for your environment.
