### ISSUE TITLE
validationEngine('validate'

### ISSUE THREAD

**Issue by tulsim** [posabsolute/jQuery-Validation-Engine#860]
Hello:

I'm new to using this plugin and need a little help.  I'm confused when to use .validationEngine('validate') as opposed to actually attaching the plugin as follows - $("#form1").validationEngine('attach', { promptPosition: "topRight" });

Thank you.

Tulsi

**Comment by mithilesh-kiprosh** [comment]
When we want to validate each single input field one by one we have to use 'validate' method of Jquery validation engine.
As, 
Suppose we have to validate name field of our form so we will use it as, 
$('#name').validationEngine('validate');
