### ISSUE TITLE
Is this being actively developed?

### ISSUE THREAD

**Issue by MB34** [posabsolute/jQuery-Validation-Engine#867]
Seems there has't been an update since 2013 and plenty of unresolved issues. Is anyone actually working on this project?

**Comment by vedmant** [comment]
Looks like it's abandoned now, I'll create a fork and make some edits for my needs.

**Comment by posabsolute** [comment]
hi, I still accept pull request & I'm looking for contributors, but now it is not actively developed

**Comment by MB34** [comment]
@vedmant One thing I added was to add blur to the bind and unbind as they didn't work correctly.
Not sure if they have been put in since 2.6.2.

While this library was ahead of it's time, here are others that are more usable but some of them aren't quite as robust, meaning they are missing some functionality. This is one that I began to use: http://formvalidation.io/
