### ISSUE TITLE
validation with ckeditor

### ISSUE THREAD

**Issue by MahmoudFawzy** [posabsolute/jQuery-Validation-Engine#877]
when i try validate textarea that I run ckeditor plugin shoing error 
http://ckeditor.com/
TypeError: field.val(...) is null
if(!required && !(field.val()) && field.val().length < 1 && $.inArray('equals', ...

**Comment by NibyP** [comment]
This solution worked for me. [https://stackoverflow.com/questions/12395239/posabsolutes-jquery-validation-engine-and-ckeditor](url)
