### ISSUE TITLE
Validate single field returns false if the field is valid and true if invalid.

### ISSUE THREAD

**Issue by evpozdniakov** [posabsolute/jQuery-Validation-Engine#891]
The results of _validate_ action for a form and for an individual field are opposite. However in documentation we can see that if there is no error, it should return true in both cases.

![validate](https://cloud.githubusercontent.com/assets/1109345/9960001/ec5268d8-5de5-11e5-9f59-98ee5b67764a.png)

**Comment by RoboSparrow** [comment]
Confirming this

https://github.com/posabsolute/jQuery-Validation-Engine/blob/master/js/jquery.validationEngine.js#L146

```
return !valid;
```
Question is whether the code is wrong or the docs.
Semantically I would expect a `true`
