### ISSUE TITLE
release notes out of date

### ISSUE THREAD

**Issue by tomchiverton** [posabsolute/jQuery-Validation-Engine#893]
http://posabsolute.github.io/jQuery-Validation-Engine/# refers to 2.6.2 but http://posabsolute.github.io/jQuery-Validation-Engine/releases.html tops out at 2.6.1

**Comment by tomchiverton** [comment]
Why was this closed @dennybrandes  ? The pages still are not in sync.

**Comment by dennybrandes** [comment]
In README file i replaced URl with link to https://github.com/posabsolute/jQuery-Validation-Engine/releases. Here we have the right releases.
