### ISSUE TITLE
Usage with JqueryUI selectmenu

### ISSUE THREAD

**Issue by Killing-Hours** [posabsolute/jQuery-Validation-Engine#899]
Hello,
Love your plugin... is the best out there... however, I've run into an issue I just can't seem to solve. 

Problem:
Using jqueryUI selecmenu... the validation is not run on the underlying select input. As a workaround... I used the jqueryUI change event on the selectmenu and ran my own validation and placement of the prompt, however, this causes other issues like the updatePromptPosition for this prompt and the form passing validation even with this select not selected. 

Question:
Is there a proper way to make validationEngine play nicely with jqueryUI selectmenu? 

JSFiddle Example:
http://jsfiddle.net/z44bprp9/5/

---

**Update**

So after toying around and playing with some things I think I've got a workaround that solves the issues.

yourCSS:
yourform select {
  display: block !important;
  visibility: hidden
}

jquery.validationEngine.js: (around line 1831)
/\* Play nice with JqueryUI */
if(field.is('select')){
  field = field.siblings('span');
}

yourJS:
$('#selectID').selectmenu({
        change: function(event,ui){
           $(this).validationEngine('validate');
        }
    });

**Comment by r4surfer** [comment]
Can you solve this : http://jsfiddle.net/z44bprp9/14/
