### ISSUE TITLE
URL validation without http/https

### ISSUE THREAD

**Issue by AtomicPenguins** [posabsolute/jQuery-Validation-Engine#904]
Hi. I want to validate a url without the http:// on it. When I put like "example.com", the error still comes up. I want to accept urls like that.

**Comment by matijatosic** [comment]
After looking all over and not finding a satisfactory response (one that doesn't include regexes), I solved it and answered here: https://stackoverflow.com/questions/12741517/how-to-make-url-validation-without-http-or-add-it-after-validation-passed/44848476#44848476
