### ISSUE TITLE
Field validations documentation

### ISSUE THREAD

**Issue by cricspy** [posabsolute/jQuery-Validation-Engine#912]
In documentation:

**validate**

Validates a form or field, displays error prompts accordingly.

Returns true if the form validates, false if it contains errors. (correct)
**_For fields, it returns true on validate and false on errors._** (wrong)

This is actually the other way. On validate it returns false and errors it returns true.

**Comment by amazingatomic** [comment]
[This one bit me today.](http://stackoverflow.com/questions/41174721/validation-engine-returns-false-when-valid)

This is a basic attribute of the plugin so correct documentation is important. This has probably bitten many more developers than just me.

Also, although this is probably only a documentation issue, I think from an API design perspective returning false when validation passes is a bit odd.
