### ISSUE TITLE
Is anyone actually helping on this project??

### ISSUE THREAD

**Issue by MB34** [posabsolute/jQuery-Validation-Engine#928]
Just wanted to know if anyone is actually monitoring these questions and helping others. Looks like there are a LOT of open issues and even bugs that don't seem to be getting any attention.

**Comment by iStefo** [comment]
Once maintainers move on to other projects and maybe even don't use this projects anymore themselves, it is not uncommon for issues to pile up.
If you are interested in taking care of issues, please let me know. But please don't expect other people to step in for you (see your other issue) when this project is merely a side-project (next to day-to-day work etc.), if it is at all.
