### ISSUE TITLE
jQuery method size() is removed

### ISSUE THREAD

**Issue by falwickster** [posabsolute/jQuery-Validation-Engine#935]
According to jQuery documentation: https://api.jquery.com/size/ method size is deprecated and removed in jQuery 3. It also suggests switching to **length** property.

**Comment by iKoala** [comment]
#937 
I made a pull request to fix this for jQuery 3.x and waiting the author to merge.

**Comment by bartclaeys** [comment]
Still seems to be a problem.

`TypeError: d.find(...).size is not a function`

**Comment by bartclaeys** [comment]
Seems like this fix has been committed, but not pushed to:

https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.js

**Comment by falwickster** [comment]
The method size has been removed from the codebase. So for me the issue is closed
