### ISSUE TITLE
When the class has ‘form-control’，the plugin dont work

### ISSUE THREAD

**Issue by OhunterO** [posabsolute/jQuery-Validation-Engine#936]
When the class has ‘form-control’，the plugin dont work。
for example：
<input class="validate[required] form-control input-sm "  type="text" value=""/>
I am using BootStrap...
Thanks

**Comment by bartclaeys** [comment]
Please provide more answers to get helped. Which jQuery version do you use. Which jQuery Validation Engine version do you use? Plus show us your code.

But on the topic, I can not replicate your bug, I'm using Bootstrap as well and use `form-control` without any problems.

**Comment by dennybrandes** [comment]
Closing cause no answer from author.
