### ISSUE TITLE
What is the latest version? 2.6.4?

### ISSUE THREAD

**Issue by bartclaeys** [posabsolute/jQuery-Validation-Engine#939]
According to https://cdnjs.com the latest version of Validation Engine is 2.6.4, but on Github the latest version is 2.6.2. How can this be explained?

Here you can select the 2.6.4 version:
https://cdnjs.com/libraries/jQuery-Validation-Engine

It's also mentioned here:
https://plugins.jquery.com/validationengine/

**Comment by dennybrandes** [comment]
2.6.5 is the latest release now
