### ISSUE TITLE
not working in angular 2

### ISSUE THREAD

**Issue by Midhilaj** [posabsolute/jQuery-Validation-Engine#949]
i included jquery validation files in index.html file

<script src="http://localhost/2017/js2/jquery.validationEngine.js" type="text/javascript"></script>
<script src="http://localhost/2017/js2/jquery.validationEngine-en.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://localhost/2017/css2/validationEngine.jquery.css">

and installed jquery in angular 2 (using npm install --save jquery and

npm install @types/jquery@2.0.47 --save-dev ) and still now it is not working .
form code
 <form id="idofurform" name="idofurform">
<input id="stdname" class="validate[ required,custom[onlyLetterNumber]] text-input form-control" type="text" name="stdname" placeholder="student name">

<input id="stdage" type="number" name="stdage" class="validate[custom[onlyNumberSp], required, custom[number],min[10],max[25]] form-control" placeholder="student age">
<input class="validate[ required, custom[email]] form-control" type="email" id="stdemail" name="stdemail" placeholder="student email">

<input maxlength="10" class="validate[custom[onlyNumberSp],required,maxSize[10],minSize[10], custom[phone]] text-input form-control" name="stdphone" id="stdphone" type="phone" name="stdphone" class="form-control">
</form> 

my ts code

constructor(){
  $(document).ready(function(){
     $("#idofurform").validationEngine();
  });
}

it showing error [ts] Property 'validationEngine' does not exist on type 'JQuery'.    
 [How to solve this issue?](https://stackoverflow.com/questions/45051634/jquery-validation-engine-in-angular-2l)

**Comment by dennybrandes** [comment]
Solution can be found here: https://stackoverflow.com/questions/45051634/jquery-validation-engine-in-angular-2
