### ISSUE TITLE
Confused about releases

### ISSUE THREAD

**Issue by zerocarbthirty** [posabsolute/jQuery-Validation-Engine#952]
I was looking at an app that uses ValidationEngine recently and I noticed that it is using version 2.6.2 but that my 2.6.2 has different files than the 2.6.2 in the zip archive. Is the latest version still 2.6.2 or is there a new version hosted somewhere else?

**Comment by bartclaeys** [comment]
Exactly, see this issue:
https://github.com/posabsolute/jQuery-Validation-Engine/issues/939

And:
https://github.com/posabsolute/jQuery-Validation-Engine/issues/940

Looks like this library is abandoned, or at least poorly managed.

**Comment by zerocarbthirty** [comment]
Is there perhaps a fork?

**Comment by dennybrandes** [comment]
We will work now on a new release 3.0.0. Starting with it, we will get better release cycles.
