### ISSUE TITLE
Incorrectly calculated TOP position with jQuery 3.3.0

### ISSUE THREAD

**Issue by svatoupravdu** [posabsolute/jQuery-Validation-Engine#959]
In jQuery 3.3.0 release something has changed and since then V.E. bubble tooltip top position is calculated differently which results in all the bubbles appearing stacked and positioned above whole page with 
`position: absolute; top: 1px;`
instead of 
`position: absolute; top: 557px;`

This must be realted to DIMENSIONS or OFFSET section of [jQ 3.3.0 changelog](http://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/)

Untill someone figures out the patch, the last working combination is jQ 3.2.1 with Validation engine 2.6.x

**Comment by calxibe** [comment]
I can confirm this problem.

A temporary workaround will be to change from field.position().xxxx to field.offset().xxxx on line 1863&1864. But this will not work correctly on pages with scroll.

**Comment by dennybrandes** [comment]
Seems to be the same as in #968

**Comment by dennybrandes** [comment]
Please check if you get same bug with version 3.0.0 of validationEngine.
