### ISSUE TITLE
Starting pre release 3.0.0

### ISSUE THREAD

**Issue by dennybrandes** [posabsolute/jQuery-Validation-Engine#969]
@posabsolute i saw that the master branch differs a lot from last release 2.6.4.
No i was thinking, how to clean it. I would suggest to create new milestone 3.0.0 and assign all issues to it which are merged into master already. Than we can create branch release-3.0.0 based on master and check everything is working. There we can include changelog file to mention to issues if possible. I will check diffs from last to master, and include changes into changelog. I everything is working fine, we can release 3.0.0 and continue we normal release cycle. I would like to contribute to this project, cause we are using it in our project and i really like it. What you think?

**Comment by posabsolute** [comment]
@dennybrandes you have been added to the collaborator list, I'm good with what you are proposing, feel free to contribute as much as you want! and thank you for helping!

**Comment by dennybrandes** [comment]
@posabsolute I created release 2.6.5 with correct version numbers. How can i update cdnjs.com?
