### ISSUE TITLE
X-Requested-With: XMLHttpRequest is not transmit in v3.0

### ISSUE THREAD

**Issue by Aigleblanc** [posabsolute/jQuery-Validation-Engine#972]
## Header HTTP

In my old site using your **v2**
<pre><code>
Host: www....
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://..............
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest      //<---------------------------------- Ok
Content-Length: 216
Connection: keep-alive
</code></pre>

On my site using your **v3**
<pre><code>
Host: ............
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: http://...........
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
//<-------------------------------------------------------------------------------------- Nok
Content-Length: 27
Origin: http://................
Connection: keep-alive
</code></pre>

In codeigniter I use _$this->input->is_ajax_request()_ but without this header, is useless.

Thank,

Have a nice day,

Fabrice,

**Comment by dennybrandes** [comment]
Hey, which jquery-version are you using? 
Best regards, Denny

**Comment by Aigleblanc** [comment]
Hi,

My admin theme use **jquery-3.2.1.min.js**

Thanks,
Fabrice
